/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e2ed",
        "inverse-primary": "#b4c5ff",
        "inverse-on-surface": "#f0f0fb",
        "background": "#faf8ff",
        "on-secondary-fixed-variant": "#005049",
        "surface": "#faf8ff",
        "surface-container-highest": "#e1e2ed",
        "outline-variant": "#c3c6d7",
        "primary-fixed": "#dbe1ff",
        "tertiary-container": "#bc4800",
        "primary": "#004ac6",
        "surface-tint": "#0053db",
        "surface-dim": "#d9d9e5",
        "on-primary-container": "#eeefff",
        "on-secondary-fixed": "#00201d",
        "tertiary": "#943700",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-surface": "#191b23",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-fixed": "#360f00",
        "secondary": "#006a61",
        "on-primary-fixed": "#00174b",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-container": "#006f66",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "secondary-fixed": "#89f5e7",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-container": "#ffede6",
        "on-background": "#191b23",
        "outline": "#737686",
        "secondary-fixed-dim": "#6bd8cb",
        "primary-container": "#2563eb",
        "surface-container-high": "#e7e7f3",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e3039",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f3fe",
        "on-error": "#ffffff",
        "secondary-container": "#86f2e4",
        "on-surface-variant": "#434655",
        "surface-bright": "#faf8ff",
        "surface-container": "#ededf9",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#7d2d00"
      },
      borderRadius: {
        "lg": "0.5rem",
        "xl": "0.75rem",
      },
      spacing: {
        "base": "4px",
        "xs": "0.25rem",
        "lg": "1.5rem",
        "md": "1rem",
        "sm": "0.5rem",
        "gutter": "1.5rem",
        "xl": "2.5rem",
        "margin": "2rem"
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "h1": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "h2": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-bold": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}